import Modal from './Modal'

const effectiveDate = '2026년 10월 6일'

function TermsContent() {
  return <div className="legal-document"><p className="legal-intro">본 약관은 커뮤니티 서비스 “모아”의 이용 조건과 운영자 및 회원의 권리·의무를 정합니다.</p><section><h3>제1조 목적 및 적용</h3><p>회원이 모아에 가입하거나 서비스를 이용하면 본 약관이 적용됩니다. 약관은 서비스 화면에 게시하며, 중요한 변경은 시행 전에 공지합니다. 회원에게 불리한 중대한 변경은 충분한 사전 안내 기간을 두고 알립니다.</p></section><section><h3>제2조 회원가입과 계정 관리</h3><p>회원은 정확한 정보를 제공해야 하며 계정과 비밀번호를 안전하게 관리할 책임이 있습니다. 다른 사람의 정보를 사용하거나 계정을 양도·대여해서는 안 됩니다. 계정 도용이 의심되면 즉시 서비스 내 문의하기를 통해 알려야 합니다.</p></section><section><h3>제3조 서비스의 제공</h3><p>모아는 게시글·댓글 작성, 반응, 조회, 문의 및 신고 기능을 제공합니다. 안정적인 운영, 보안, 점검 또는 불가피한 사유가 있을 때 서비스의 전부나 일부를 일시적으로 제한할 수 있으며 가능한 경우 사전에 안내합니다.</p></section><section><h3>제4조 회원의 의무</h3><ul><li>법령 또는 다른 사람의 권리·명예·사생활을 침해하는 콘텐츠를 게시하지 않습니다.</li><li>욕설, 괴롭힘, 음란물, 개인정보 노출, 스팸·광고, 악성 코드 또는 서비스 운영을 방해하는 행위를 하지 않습니다.</li><li>신고·문의 기능을 허위 또는 반복적으로 남용하지 않습니다.</li></ul></section><section><h3>제5조 게시물과 이용 허락</h3><p>회원이 작성한 콘텐츠의 권리는 원칙적으로 작성자에게 있습니다. 회원은 서비스 운영·표시·백업에 필요한 범위에서 모아가 해당 콘텐츠를 이용할 수 있도록 허락합니다. 서비스 외 홍보나 별도 영리 이용이 필요한 경우에는 추가 동의를 받습니다.</p></section><section><h3>제6조 게시물 관리와 이용 제한</h3><p>운영자는 법령 위반, 권리 침해, 개인정보 노출, 스팸, 음란·폭력적 콘텐츠 또는 운영 정책 위반이 확인되면 게시물이나 댓글을 숨김·삭제하고 계정 이용을 제한할 수 있습니다. 신고는 검토 후 처리하며, 필요한 경우 당사자에게 소명 기회를 제공합니다.</p></section><section><h3>제7조 이용 종료</h3><p>회원은 서비스 내 문의하기를 통해 탈퇴 또는 개인정보 삭제를 요청할 수 있습니다. 탈퇴 시 관계 법령이나 분쟁 처리를 위해 보관할 필요가 있는 정보를 제외하고 개인정보를 파기합니다. 다른 회원과 공유된 게시물은 별도 삭제 요청이 필요할 수 있습니다.</p></section><section><h3>제8조 책임의 범위</h3><p>운영자는 고의 또는 중대한 과실이 없는 한 천재지변, 통신 장애, 회원의 귀책사유 등 통제하기 어려운 사유로 발생한 손해에 책임을 지지 않습니다. 이 조항은 관련 법령에 따른 운영자의 책임을 부당하게 제한하지 않습니다.</p></section><section><h3>제9조 분쟁 해결</h3><p>분쟁이 발생하면 상호 협의를 통해 해결하도록 노력하며, 해결되지 않는 경우 대한민국 법령과 민사소송법상 관할 법원에 따릅니다.</p></section><p className="legal-date">시행일: {effectiveDate}</p><LegalReferences type="terms" /></div>
}

function PrivacyContent() {
  return <div className="legal-document"><p className="legal-intro">모아 운영팀은 개인정보 보호법에 따라 이용자의 개인정보를 안전하게 처리하고 권리를 보호하기 위해 다음과 같이 안내합니다.</p><section><h3>1. 처리하는 개인정보와 목적</h3><div className="legal-table-wrap"><table><thead><tr><th>구분</th><th>항목</th><th>목적</th></tr></thead><tbody><tr><td>회원가입</td><td>이름, 닉네임, 이메일, 비밀번호 인증정보</td><td>회원 식별, 로그인, 계정 관리</td></tr><tr><td>서비스 이용</td><td>게시글, 댓글, 반응, 조회 기록</td><td>커뮤니티 기능 제공 및 운영</td></tr><tr><td>고객지원</td><td>문의·신고 내용과 처리 기록</td><td>문의 답변, 신고 검토, 분쟁 대응</td></tr><tr><td>자동 생성</td><td>접속 로그, IP 주소, 브라우저·기기 정보</td><td>보안, 오류 분석, 부정 이용 방지</td></tr></tbody></table></div><p>비밀번호는 인증 시스템에서 암호화된 방식으로 처리되며 운영자가 평문으로 확인하지 않습니다.</p></section><section><h3>2. 보유 및 이용 기간</h3><p>개인정보는 회원 탈퇴 또는 처리 목적 달성 시까지 보유한 뒤 지체 없이 파기합니다. 다만 관계 법령 준수, 권리 침해 대응 또는 진행 중인 분쟁 처리를 위해 필요한 경우 해당 목적에 필요한 최소 범위와 기간 동안 분리하여 보관할 수 있습니다.</p></section><section><h3>3. 제3자 제공</h3><p>모아는 이용자의 개인정보를 원칙적으로 제3자에게 판매하거나 제공하지 않습니다. 법령상 의무가 있거나 이용자가 사전에 동의한 경우에만 필요한 범위에서 제공합니다.</p></section><section><h3>4. 처리 업무의 위탁 및 국외 처리</h3><ul><li><strong>Supabase:</strong> 회원 인증, 데이터베이스 및 백엔드 인프라 운영</li><li><strong>Vercel:</strong> 프런트엔드 호스팅과 콘텐츠 전송</li></ul><p>서비스 제공 과정에서 위 사업자의 해외 데이터센터를 통해 정보가 저장·처리될 수 있습니다. 운영자는 위탁 사업자를 점검하고 계약 및 보안 설정을 통해 개인정보가 안전하게 처리되도록 관리합니다. 실제 운영 리전이나 위탁 조건이 변경되면 본 방침을 갱신합니다.</p></section><section><h3>5. 파기 절차와 방법</h3><p>보유 목적이 끝난 개인정보는 복구하거나 재생할 수 없도록 전자 파일을 안전하게 삭제합니다. 법령에 따라 별도 보관하는 정보는 다른 정보와 분리하여 접근을 제한합니다.</p></section><section><h3>6. 이용자의 권리</h3><p>이용자는 자신의 개인정보에 대해 열람, 정정, 삭제, 처리정지 및 동의 철회를 요청할 수 있습니다. 요청은 프로필의 문의하기 기능을 통해 접수할 수 있으며, 본인 확인 후 관계 법령에서 정한 절차에 따라 처리 결과를 안내합니다.</p></section><section><h3>7. 안전성 확보 조치</h3><p>접근 권한 제한, 인증정보 보호, 전송 구간 암호화, 접속 기록 관리, 보안 업데이트 등 개인정보 보호에 필요한 기술적·관리적 조치를 적용합니다.</p></section><section><h3>8. 쿠키와 로컬 저장소</h3><p>로그인 유지와 공지사항의 “24시간 동안 보지 않기” 기능을 위해 브라우저 저장소를 사용합니다. 브라우저 설정에서 이를 삭제하거나 차단할 수 있으나 일부 기능 이용이 제한될 수 있습니다.</p></section><section><h3>9. 개인정보 보호 문의</h3><p>개인정보 관련 문의, 불만 또는 권리 행사는 프로필의 문의하기 기능을 이용해 주세요. 개인정보 보호 담당인 모아 운영팀이 확인 후 답변합니다.</p></section><section><h3>10. 방침 변경</h3><p>법령 또는 서비스 변경으로 본 방침이 바뀌는 경우 시행 전에 공지사항을 통해 변경 내용과 시행일을 알립니다.</p></section><div className="legal-draft-note"><strong>운영 전 확인 필요</strong><p>본 문서는 현재 서비스 기능을 기준으로 작성한 기본 초안입니다. 실제 운영 주체의 명칭·주소·연락처, 개인정보 보호책임자, 서버 리전, 위탁 및 국외이전 세부사항을 확정한 뒤 법률 전문가의 검토를 권장합니다.</p></div><p className="legal-date">시행일: {effectiveDate}</p><LegalReferences type="privacy" /></div>
}

function LegalReferences({ type }) {
  return <div className="legal-references"><strong>작성 참고</strong>{type === 'terms' ? <a href="https://www.law.go.kr/LSW/lsInfoP.do?lsiSeq=253655" target="_blank" rel="noreferrer">약관의 규제에 관한 법률</a> : <><a href="https://www.law.go.kr/lsLinkCommonInfo.do?lsJoLnkSeq=1029334949" target="_blank" rel="noreferrer">개인정보 보호법 제30조</a><a href="https://www.law.go.kr/LSW/LsiJoLinkP.do?docType=JO&joNo=002200000&languageType=KO&lsNm=%EA%B0%9C%EC%9D%B8%EC%A0%95%EB%B3%B4+%EB%B3%B4%ED%98%B8%EB%B2%95&paras=1" target="_blank" rel="noreferrer">개인정보 열람·정정·삭제 권리</a></>}</div>
}

function LegalModal({ type, onClose }) {
  return <Modal title={type === 'terms' ? '이용약관' : '개인정보처리방침'} size="large" onClose={onClose}>{type === 'terms' ? <TermsContent /> : <PrivacyContent />}</Modal>
}

export default LegalModal
