begin;

drop view if exists public.post_summaries;
drop view if exists public.comment_details;

create table public.profiles (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  name text not null,
  nickname text not null unique,
  bio text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.profiles (user_id, name, nickname, bio, created_at, updated_at)
select id, name, nickname, bio, created_at, updated_at
from public.users
on conflict (user_id) do nothing;

alter table public.users
  drop column name,
  drop column nickname,
  drop column bio;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

create or replace view public.user_details
with (security_invoker = true) as
select u.id, u.auth_user_id, u.email, u.created_at, u.updated_at,
  p.id as profile_id, p.name, p.nickname, p.bio,
  p.created_at as profile_created_at, p.updated_at as profile_updated_at
from public.users u
left join public.profiles p on p.user_id = u.id;

create or replace view public.post_summaries
with (security_invoker = true) as
select p.id, p.user_id, p.category, p.title, p.content, p.view_count, p.is_hidden,
  p.created_at, p.updated_at, coalesce(pr.nickname, u.email) as author, u.email as author_email,
  (select count(*) from public.comments c where c.post_id = p.id and not c.is_hidden) as comment_count,
  (select count(*) from public.post_reactions r where r.post_id = p.id and r.reaction = 'like') as like_count,
  (select count(*) from public.post_reactions r where r.post_id = p.id and r.reaction = 'dislike') as dislike_count
from public.posts p
join public.users u on u.id = p.user_id
left join public.profiles pr on pr.user_id = u.id;

create or replace view public.comment_details
with (security_invoker = true) as
select c.id, c.post_id, c.user_id, c.content, c.is_hidden, c.created_at, c.updated_at,
  coalesce(pr.nickname, u.email) as author, u.email as author_email, p.title as post_title
from public.comments c
join public.users u on u.id = c.user_id
left join public.profiles pr on pr.user_id = u.id
join public.posts p on p.id = c.post_id;

alter table public.profiles enable row level security;
revoke all on table public.profiles from anon, authenticated;
revoke all on table public.user_details, public.post_summaries, public.comment_details from anon, authenticated;
grant all on table public.profiles to service_role;
grant select on table public.user_details, public.post_summaries, public.comment_details to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.sync_identity_sequences()
returns void language plpgsql security definer set search_path = '' as $$
begin
  perform setval(pg_get_serial_sequence('public.admins', 'id'), coalesce((select max(id) from public.admins), 1), exists(select 1 from public.admins));
  perform setval(pg_get_serial_sequence('public.users', 'id'), coalesce((select max(id) from public.users), 1), exists(select 1 from public.users));
  perform setval(pg_get_serial_sequence('public.profiles', 'id'), coalesce((select max(id) from public.profiles), 1), exists(select 1 from public.profiles));
  perform setval(pg_get_serial_sequence('public.posts', 'id'), coalesce((select max(id) from public.posts), 1), exists(select 1 from public.posts));
  perform setval(pg_get_serial_sequence('public.comments', 'id'), coalesce((select max(id) from public.comments), 1), exists(select 1 from public.comments));
end;
$$;
revoke all on function public.sync_identity_sequences() from public, anon, authenticated;
grant execute on function public.sync_identity_sequences() to service_role;

commit;
