create extension if not exists pgcrypto with schema extensions;

create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  email text not null unique check (email = lower(email)),
  password_hash text not null,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text not null unique check (email = lower(email)),
  password_hash text not null,
  name text not null,
  nickname text not null unique,
  bio text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  category text not null default '자유',
  title text not null check (char_length(title) between 1 and 80),
  content text not null check (char_length(content) > 0),
  view_count integer not null default 0 check (view_count >= 0),
  is_hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 2000),
  is_hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.post_views (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  viewed_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.post_reactions (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  reaction text not null check (reaction in ('like', 'dislike')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create index if not exists idx_posts_created_at on public.posts(created_at desc);
create index if not exists idx_posts_category on public.posts(category);
create index if not exists idx_comments_post_id on public.comments(post_id, created_at);
create index if not exists idx_post_reactions_post_id on public.post_reactions(post_id);

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists admins_set_updated_at on public.admins;
create trigger admins_set_updated_at before update on public.admins
for each row execute function public.set_updated_at();
drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at before update on public.users
for each row execute function public.set_updated_at();
drop trigger if exists posts_set_updated_at on public.posts;
create trigger posts_set_updated_at before update on public.posts
for each row execute function public.set_updated_at();
drop trigger if exists comments_set_updated_at on public.comments;
create trigger comments_set_updated_at before update on public.comments
for each row execute function public.set_updated_at();
drop trigger if exists post_reactions_set_updated_at on public.post_reactions;
create trigger post_reactions_set_updated_at before update on public.post_reactions
for each row execute function public.set_updated_at();

create or replace view public.post_summaries
with (security_invoker = true) as
select p.id, p.user_id, p.category, p.title, p.content, p.view_count, p.is_hidden,
  p.created_at, p.updated_at, u.nickname as author, u.email as author_email,
  (select count(*) from public.comments c where c.post_id = p.id and not c.is_hidden) as comment_count,
  (select count(*) from public.post_reactions r where r.post_id = p.id and r.reaction = 'like') as like_count,
  (select count(*) from public.post_reactions r where r.post_id = p.id and r.reaction = 'dislike') as dislike_count
from public.posts p
join public.users u on u.id = p.user_id;

create or replace view public.comment_details
with (security_invoker = true) as
select c.id, c.post_id, c.user_id, c.content, c.is_hidden, c.created_at, c.updated_at,
  u.nickname as author, u.email as author_email, p.title as post_title
from public.comments c
join public.users u on u.id = c.user_id
join public.posts p on p.id = c.post_id;

create or replace function public.record_post_view(p_post_id bigint, p_user_id bigint)
returns integer language plpgsql security definer set search_path = '' as $$
declare
  inserted_count integer;
  current_views integer;
begin
  if not exists (select 1 from public.posts where id = p_post_id and not is_hidden) then
    raise exception 'POST_NOT_FOUND';
  end if;

  insert into public.post_views(post_id, user_id) values (p_post_id, p_user_id)
  on conflict do nothing;
  get diagnostics inserted_count = row_count;

  if inserted_count > 0 then
    update public.posts set view_count = view_count + 1 where id = p_post_id;
  end if;
  select view_count into current_views from public.posts where id = p_post_id;
  return current_views;
end;
$$;

create or replace function public.set_post_reaction(p_post_id bigint, p_user_id bigint, p_reaction text)
returns table(likes bigint, dislikes bigint)
language plpgsql security definer set search_path = '' as $$
begin
  if p_reaction is not null and p_reaction not in ('like', 'dislike') then
    raise exception 'INVALID_REACTION';
  end if;
  if not exists (select 1 from public.posts where id = p_post_id and not is_hidden) then
    raise exception 'POST_NOT_FOUND';
  end if;

  delete from public.post_reactions where post_id = p_post_id and user_id = p_user_id;
  if p_reaction is not null then
    insert into public.post_reactions(post_id, user_id, reaction)
    values (p_post_id, p_user_id, p_reaction);
  end if;

  return query select
    count(*) filter (where reaction = 'like'),
    count(*) filter (where reaction = 'dislike')
  from public.post_reactions where post_id = p_post_id;
end;
$$;

alter table public.admins enable row level security;
alter table public.users enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.post_views enable row level security;
alter table public.post_reactions enable row level security;

revoke all on table public.admins, public.users, public.posts, public.comments, public.post_views, public.post_reactions from anon, authenticated;
revoke all on table public.post_summaries, public.comment_details from anon, authenticated;
revoke all on function public.record_post_view(bigint, bigint) from public, anon, authenticated;
revoke all on function public.set_post_reaction(bigint, bigint, text) from public, anon, authenticated;
grant all on table public.admins, public.users, public.posts, public.comments, public.post_views, public.post_reactions to service_role;
grant usage, select on all sequences in schema public to service_role;
grant select on table public.post_summaries, public.comment_details to service_role;
grant execute on function public.record_post_view(bigint, bigint) to service_role;
grant execute on function public.set_post_reaction(bigint, bigint, text) to service_role;

create or replace function public.sync_identity_sequences()
returns void language plpgsql security definer set search_path = '' as $$
begin
  perform setval(pg_get_serial_sequence('public.admins', 'id'), coalesce((select max(id) from public.admins), 1), exists(select 1 from public.admins));
  perform setval(pg_get_serial_sequence('public.users', 'id'), coalesce((select max(id) from public.users), 1), exists(select 1 from public.users));
  perform setval(pg_get_serial_sequence('public.posts', 'id'), coalesce((select max(id) from public.posts), 1), exists(select 1 from public.posts));
  perform setval(pg_get_serial_sequence('public.comments', 'id'), coalesce((select max(id) from public.comments), 1), exists(select 1 from public.comments));
end;
$$;
revoke all on function public.sync_identity_sequences() from public, anon, authenticated;
grant execute on function public.sync_identity_sequences() to service_role;
