create table public.notices (
  id bigint generated by default as identity primary key,
  admin_id bigint not null references public.admins(id) on delete restrict,
  title text not null check (char_length(title) between 1 and 120),
  content text not null check (char_length(content) between 1 and 5000),
  is_active boolean not null default true,
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at is null or ends_at > starts_at)
);

create table public.inquiries (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 120),
  content text not null check (char_length(content) between 1 and 3000),
  status text not null default 'pending' check (status in ('pending', 'answered', 'closed')),
  answer text check (answer is null or char_length(answer) between 1 and 5000),
  answered_by bigint references public.admins(id) on delete set null,
  answered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.reports (
  id bigint generated by default as identity primary key,
  reporter_id bigint not null references public.users(id) on delete cascade,
  target_type text not null check (target_type in ('post', 'comment')),
  post_id bigint references public.posts(id) on delete set null,
  comment_id bigint references public.comments(id) on delete set null,
  target_title text not null,
  target_content text not null,
  target_author text not null,
  reason text not null check (reason in ('spam', 'abuse', 'obscene', 'privacy', 'other')),
  details text not null check (char_length(details) between 1 and 2000),
  status text not null default 'pending' check (status in ('pending', 'reviewing', 'resolved', 'dismissed')),
  admin_note text check (admin_note is null or char_length(admin_note) <= 2000),
  handled_by bigint references public.admins(id) on delete set null,
  handled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_notices_active on public.notices(is_active, starts_at desc);
create index idx_inquiries_user on public.inquiries(user_id, created_at desc);
create index idx_inquiries_status on public.inquiries(status, created_at desc);
create index idx_reports_status on public.reports(status, created_at desc);
create index idx_reports_reporter on public.reports(reporter_id, created_at desc);

create trigger notices_set_updated_at before update on public.notices
for each row execute function public.set_updated_at();
create trigger inquiries_set_updated_at before update on public.inquiries
for each row execute function public.set_updated_at();
create trigger reports_set_updated_at before update on public.reports
for each row execute function public.set_updated_at();

create view public.notice_details
with (security_invoker = true) as
select n.*, a.name as admin_name
from public.notices n
join public.admins a on a.id = n.admin_id;

create view public.inquiry_details
with (security_invoker = true) as
select i.*, u.email as user_email, coalesce(p.nickname, u.email) as user_name,
  a.name as answered_by_name
from public.inquiries i
join public.users u on u.id = i.user_id
left join public.profiles p on p.user_id = u.id
left join public.admins a on a.id = i.answered_by;

create view public.report_details
with (security_invoker = true) as
select r.*, u.email as reporter_email, coalesce(p.nickname, u.email) as reporter_name,
  a.name as handled_by_name
from public.reports r
join public.users u on u.id = r.reporter_id
left join public.profiles p on p.user_id = u.id
left join public.admins a on a.id = r.handled_by;

alter table public.notices enable row level security;
alter table public.inquiries enable row level security;
alter table public.reports enable row level security;

revoke all on table public.notices, public.inquiries, public.reports from anon, authenticated;
revoke all on table public.notice_details, public.inquiry_details, public.report_details from anon, authenticated;
grant all on table public.notices, public.inquiries, public.reports to service_role;
grant select on table public.notice_details, public.inquiry_details, public.report_details to service_role;
grant usage, select on all sequences in schema public to service_role;
